<a href="https://colab.research.google.com/github/enzokai1/Calculo-Numerico/blob/main/Atividade_4_CN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cálculo Numérico — Lista de Exercícios
**Sistemas lineares e implementação numérica**

**Enzo Massahiro Nogueira Kai - RA:187385**

Resolução completa: parte manual (Markdown/LaTeX) + implementação em Python.
Execute as células de código em ordem (Runtime ▸ Run all).

## Parte 1 — Conceitos e resolução manual

### Exercício 1 — Forma matricial $A\mathbf{x}=\mathbf{b}$

**a)**
$$
\underbrace{\begin{bmatrix}2 & 1\\ 1 & -3\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\ y\end{bmatrix}}_{\mathbf{x}}
=
\underbrace{\begin{bmatrix}7\\ -5\end{bmatrix}}_{\mathbf{b}}
$$

**b)**
$$
\underbrace{\begin{bmatrix}1 & 2 & -1\\ 3 & -1 & 2\\ 2 & 1 & 1\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\ y\\ z\end{bmatrix}}_{\mathbf{x}}
=
\underbrace{\begin{bmatrix}2\\ 9\\ 7\end{bmatrix}}_{\mathbf{b}}
$$

> Regra: cada **linha** de $A$ guarda os coeficientes de uma equação; $\mathbf{x}$ lista as incógnitas na ordem das colunas; $\mathbf{b}$ guarda os termos independentes.

In [1]:
import numpy as np

# Exercício 1 — conferindo a forma matricial (e as soluções, só para verificar)
A1a = np.array([[2, 1], [1, -3]], dtype=float);           b1a = np.array([7, -5], dtype=float)
A1b = np.array([[1, 2, -1], [3, -1, 2], [2, 1, 1]], dtype=float); b1b = np.array([2, 9, 7], dtype=float)

print("1a) A =\n", A1a, "\n    b =", b1a, "\n    solução:", np.linalg.solve(A1a, b1a))
print("1b) A =\n", A1b, "\n    b =", b1b, "\n    solução:", np.linalg.solve(A1b, b1b))

1a) A =
 [[ 2.  1.]
 [ 1. -3.]] 
    b = [ 7. -5.] 
    solução: [2.28571429 2.42857143]
1b) A =
 [[ 1.  2. -1.]
 [ 3. -1.  2.]
 [ 2.  1.  1.]] 
    b = [2. 9. 7.] 
    solução: [2. 1. 2.]


### Exercício 2 — Eliminação de Gauss

Sistema:
$$
\begin{cases} 2x + y - z = 8\\ -3x - y + 2z = -11\\ -2x + y + 2z = -3 \end{cases}
$$

**Matriz aumentada inicial**
$$
\left[\begin{array}{ccc|c} 2 & 1 & -1 & 8\\ -3 & -1 & 2 & -11\\ -2 & 1 & 2 & -3 \end{array}\right]
$$

**Passo 1 — zerar a 1ª coluna** (pivô $a_{11}=2$)

$L_2 \leftarrow L_2 + \tfrac{3}{2}L_1$  (multiplicador $m_{21}=-3/2$)  
$L_3 \leftarrow L_3 + L_1$  (multiplicador $m_{31}=-1$)

$$
\left[\begin{array}{ccc|c} 2 & 1 & -1 & 8\\ 0 & \tfrac12 & \tfrac12 & 1\\ 0 & 2 & 1 & 5 \end{array}\right]
$$

**Passo 2 — zerar a 2ª coluna** (pivô $a_{22}=\tfrac12$)

$L_3 \leftarrow L_3 - 4L_2$  (multiplicador $m_{32}=2/(1/2)=4$)

$$
\left[\begin{array}{ccc|c} 2 & 1 & -1 & 8\\ 0 & \tfrac12 & \tfrac12 & 1\\ 0 & 0 & -1 & 1 \end{array}\right]
$$

**Substituição regressiva**

- $-z = 1 \Rightarrow z = -1$
- $\tfrac12 y + \tfrac12(-1) = 1 \Rightarrow y = 3$
- $2x + 3 - (-1) = 8 \Rightarrow 2x = 4 \Rightarrow x = 2$

$$\boxed{(x,y,z) = (2,\,3,\,-1)}$$

**Verificação:** $2(2)+3+1=8$ ✓; $-6-3-2=-11$ ✓; $-4+3-2=-3$ ✓

## Parte 2 — Propriedades e interpretação

### Exercício 3 — Número de soluções

**a)** $\begin{cases} x+y=3\\ 2x+2y=6\end{cases}$

$$\left[\begin{array}{cc|c} 1&1&3\\ 2&2&6\end{array}\right]\xrightarrow{L_2\leftarrow L_2-2L_1}\left[\begin{array}{cc|c} 1&1&3\\ 0&0&0\end{array}\right]$$

Linha $0=0$ (sempre verdadeira) e $\text{posto}(A)=\text{posto}([A|b])=1<2$ incógnitas → **infinitas soluções**: $x = 3 - y$, com $y$ livre.

**b)** $\begin{cases} x+y=3\\ 2x+2y=7\end{cases}$

$$\left[\begin{array}{cc|c} 1&1&3\\ 2&2&7\end{array}\right]\xrightarrow{L_2\leftarrow L_2-2L_1}\left[\begin{array}{cc|c} 1&1&3\\ 0&0&1\end{array}\right]$$

Linha $0=1$ (absurdo): $\text{posto}(A)=1\neq\text{posto}([A|b])=2$ → **nenhuma solução** (sistema impossível).

**c)** $\begin{cases} x+y=3\\ 2x-y=0\end{cases}$

$$\left[\begin{array}{cc|c} 1&1&3\\ 2&-1&0\end{array}\right]\xrightarrow{L_2\leftarrow L_2-2L_1}\left[\begin{array}{cc|c} 1&1&3\\ 0&-3&-6\end{array}\right]$$

$-3y=-6\Rightarrow y=2$; $x+2=3\Rightarrow x=1$. Posto $=2=$ nº de incógnitas → **solução única**: $(x,y)=(1,2)$.

> **Mnemônico (Rouché–Capelli):** posto$(A)$ ≠ posto$([A|b])$ → *nenhuma*; iguais e $=n$ → *única*; iguais e $<n$ → *infinitas*.

In [2]:
# Exercício 3 — conferência numérica via posto (Rouché–Capelli)
def classifica(A, b):
    A = np.array(A, dtype=float); b = np.array(b, dtype=float)
    n = A.shape[1]
    rA  = np.linalg.matrix_rank(A)
    rAb = np.linalg.matrix_rank(np.column_stack([A, b]))
    if rA != rAb:  return f"posto(A)={rA}, posto([A|b])={rAb} -> NENHUMA solução"
    if rA == n:    return f"posto(A)={rA}, posto([A|b])={rAb} -> solução ÚNICA"
    return f"posto(A)={rA}, posto([A|b])={rAb} -> INFINITAS soluções"

print("3a)", classifica([[1, 1], [2, 2]], [3, 6]))
print("3b)", classifica([[1, 1], [2, 2]], [3, 7]))
print("3c)", classifica([[1, 1], [2, -1]], [3, 0]))

3a) posto(A)=1, posto([A|b])=1 -> INFINITAS soluções
3b) posto(A)=1, posto([A|b])=2 -> NENHUMA solução
3c) posto(A)=2, posto([A|b])=2 -> solução ÚNICA


## Parte 3 — Implementação numérica em Python

### Exercício 4 — Eliminação de Gauss sem pivoteamento

In [3]:
import numpy as np

def gauss_sem_pivoteamento(A, b, verbose=False):
    '''
    Resolve Ax = b por eliminação de Gauss SEM pivoteamento.
    Retorna o vetor solução x.
    '''
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1, 1)
    n = A.shape[0]

    # 1) Forma a matriz aumentada [A | b]
    M = np.hstack([A, b])
    if verbose:
        print("Matriz aumentada inicial:\n", M, "\n")

    # 2) Eliminação: zera os elementos abaixo de cada pivô
    for k in range(n - 1):
        pivo = M[k, k]
        if abs(pivo) < 1e-12:
            raise ZeroDivisionError(f"Pivô nulo na posição ({k},{k}); seria necessário pivoteamento.")
        for i in range(k + 1, n):
            m = M[i, k] / pivo              # multiplicador
            M[i, k:] = M[i, k:] - m * M[k, k:]   # Li <- Li - m * Lk
        if verbose:
            print(f"Após eliminar a coluna {k}:\n", np.round(M, 6), "\n")

    if abs(M[n - 1, n - 1]) < 1e-12:
        raise ZeroDivisionError("Último pivô nulo: sistema singular.")

    # 3) Substituição regressiva
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (M[i, n] - M[i, i + 1:n] @ x[i + 1:]) / M[i, i]

    return x

# Teste com o sistema do exercício 2
A2 = [[2, 1, -1], [-3, -1, 2], [-2, 1, 2]]
b2 = [8, -11, -3]

x_gauss = gauss_sem_pivoteamento(A2, b2, verbose=True)
x_numpy = np.linalg.solve(A2, b2)

print("Solução (Gauss implementado):", x_gauss)
print("Solução (numpy.linalg.solve):", x_numpy)
print("Diferença máxima |x_gauss - x_numpy| =", np.max(np.abs(x_gauss - x_numpy)))
print("Resíduo ||Ax - b|| =", np.linalg.norm(np.array(A2) @ x_gauss - b2))

Matriz aumentada inicial:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]] 

Após eliminar a coluna 0:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]] 

Após eliminar a coluna 1:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]] 

Solução (Gauss implementado): [ 2.  3. -1.]
Solução (numpy.linalg.solve): [ 2.  3. -1.]
Diferença máxima |x_gauss - x_numpy| = 5.551115123125783e-16
Resíduo ||Ax - b|| = 0.0


**Interpretação:** a solução obtida é $(x,y,z)=(2,3,-1)$, igual à resolução manual e à de `numpy.linalg.solve` (a diferença fica na ordem de $10^{-15}$, erro de arredondamento de ponto flutuante). O `np.linalg.solve` usa fatoração LU **com pivoteamento parcial**, por isso é mais robusto; o nosso algoritmo falha se algum pivô for zero (ou muito pequeno), caso em que trocar linhas seria necessário.

## Parte 4 — Aplicação

### Exercício 5 — Balanço térmico

$$
\begin{bmatrix}4&-1&0\\-1&4&-1\\0&-1&3\end{bmatrix}
\begin{bmatrix}T_1\\T_2\\T_3\end{bmatrix}=
\begin{bmatrix}15\\10\\10\end{bmatrix}
$$

**a) Resolução manual**

$$\left[\begin{array}{ccc|c} 4&-1&0&15\\ -1&4&-1&10\\ 0&-1&3&10\end{array}\right]$$

**Passo 1** (pivô $4$): $L_2\leftarrow L_2+\tfrac14 L_1$ ($m_{21}=-1/4$); $L_3$ já tem 0 na 1ª coluna.

$$\left[\begin{array}{ccc|c} 4&-1&0&15\\ 0&\tfrac{15}{4}&-1&\tfrac{55}{4}\\ 0&-1&3&10\end{array}\right]$$

**Passo 2** (pivô $\tfrac{15}{4}$): $m_{32}=-1/(15/4)=-\tfrac{4}{15}$, logo $L_3\leftarrow L_3+\tfrac{4}{15}L_2$:

- $3-\tfrac{4}{15}=\tfrac{41}{15}$
- $10+\tfrac{4}{15}\cdot\tfrac{55}{4}=10+\tfrac{55}{15}=\tfrac{205}{15}$

$$\left[\begin{array}{ccc|c} 4&-1&0&15\\ 0&\tfrac{15}{4}&-1&\tfrac{55}{4}\\ 0&0&\tfrac{41}{15}&\tfrac{205}{15}\end{array}\right]$$

**Substituição regressiva**

- $\tfrac{41}{15}T_3=\tfrac{205}{15}\Rightarrow T_3=5$
- $\tfrac{15}{4}T_2-5=\tfrac{55}{4}\Rightarrow T_2=5$
- $4T_1-5=15\Rightarrow T_1=5$

$$\boxed{T_1=T_2=T_3=5}$$

**Verificação:** $4(5)-5=15$ ✓; $-5+20-5=10$ ✓; $-5+15=10$ ✓

**b) Implementação em Python** (reutilizando a função do exercício 4)

In [4]:
A5 = [[4, -1, 0], [-1, 4, -1], [0, -1, 3]]
b5 = [15, 10, 10]

T = gauss_sem_pivoteamento(A5, b5)
T_np = np.linalg.solve(A5, b5)

for i, t in enumerate(T, start=1):
    print(f"T{i} = {t:.6f}")
print("numpy.linalg.solve:", T_np)
print("Resíduo ||AT - b|| =", np.linalg.norm(np.array(A5) @ T - b5))

T1 = 5.000000
T2 = 5.000000
T3 = 5.000000
numpy.linalg.solve: [5. 5. 5.]
Resíduo ||AT - b|| = 0.0


**Interpretação:** as três temperaturas de equilíbrio são iguais a $5$. A matriz é **diagonalmente dominante** (em cada linha, $|a_{ii}|$ é estritamente maior que a soma dos módulos dos demais elementos: $4>1$, $4>2$, $3>1$), o que garante pivôs não nulos — por isso a eliminação sem pivoteamento funciona bem aqui.

---
## Resumo das respostas

| Ex. | Resposta |
|---|---|
| 2 | $(x,y,z)=(2,3,-1)$ |
| 3a | Infinitas soluções |
| 3b | Nenhuma solução |
| 3c | Única: $(1,2)$ |
| 5 | $T_1=T_2=T_3=5$ |